name: release

on:
  push:
    branches:
      - master

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.1
      - run: npm audit --audit-level=moderate

  test:
    needs: audit

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [12, 13, 14]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}

      - uses: actions/setup-node@v2.1.1
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm ci
      - run: npm run test

  release:
    needs: test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-semantic-release@v1
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN || secrets.GITHUB_TOKEN }}
